Lmod has detected the following error: The following module(s) are unknown:
"python/3.13.1"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "python/3.13.1"

Also make sure that all modulefiles written in TCL start with the string
#%Module



INFO:atlite.cutout:Building new cutout europe_1x1.nc
Traceback (most recent call last):
  File "/home/s233224/anaconda3/lib/python3.12/site-packages/atlite/cutout.py", line 173, in __init__
    module = cutoutparams.pop("module")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'module'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/users/s233224/Climate-Change-Impacted-Solar-Energy-Generation/script_cutout.py", line 15, in <module>
    cutout_1x1 = atlite.Cutout(
                 ^^^^^^^^^^^^^^
  File "/home/s233224/anaconda3/lib/python3.12/site-packages/atlite/cutout.py", line 175, in __init__
    raise TypeError(
TypeError: Arguments 'time' and 'module' must be specified. Spatial bounds must either be passed via argument 'bounds' or 'x' and 'y'.
