Lmod has detected the following error: The following module(s) are unknown:
"python/3.13.1"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "python/3.13.1"

Also make sure that all modulefiles written in TCL start with the string
#%Module



Traceback (most recent call last):
  File "/work/users/s233224/Climate-Change-Impacted-Solar-Energy-Generation/script_cutout.py", line 15, in <module>
    cutout_2014 = atlite.Cutout(
                  ^^^^^^^^^^^^^^
  File "/home/s233224/anaconda3/lib/python3.12/site-packages/atlite/cutout.py", line 153, in __init__
    data = data.chunk(chunks)
           ^^^^^^^^^^^^^^^^^^
  File "/home/s233224/anaconda3/lib/python3.12/site-packages/xarray/core/dataset.py", line 2817, in chunk
    raise ValueError(
ValueError: chunks keys ('lon', 'lat') not found in data dimensions ('x', 'y', 'time')
